package com.nitk.it.glassassistant;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.media.AudioManager;
import android.os.Bundle;
import android.speech.tts.TextToSpeech;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import java.io.File;
import java.util.Locale;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class CaptionActivity extends Activity {

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    private CardScrollView mCardScroller;

    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    private View mView;

    private String caption;
    private File imageFile;
    private TextToSpeech textToSpeech;

    @Override
    protected void onCreate(Bundle bundle) {
        System.out.println("Entering CaptionActivity onCreate");
        super.onCreate(bundle);
        imageFile = (File) getIntent().getExtras().get("IMAGE");
        caption = (String) getIntent().getExtras().get("CAPTION");

        mView = buildView();

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });
        // Handle the TAP event.
        mCardScroller.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Plays disallowed sound to indicate that TAP actions are not supported.
                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                am.playSoundEffect(Sounds.DISALLOWED);
            }
        });
        setContentView(mCardScroller);
        textToSpeech = new TextToSpeech(getApplicationContext(), new TextToSpeech.OnInitListener() {
            @Override
            public void onInit(int status) {
                if (status != TextToSpeech.ERROR) {
                    System.out.println("Entering CaptionActivity TextToSpeech.onInit");
                    textToSpeech.setLanguage(Locale.US);
                    textToSpeech.speak(caption, TextToSpeech.QUEUE_FLUSH, null);
                    generateAudioSignal();
                }
            }
        });
    }

    private void generateAudioSignal() {
        System.out.println("Entering CaptionActivity generateAudioSignal");
        textToSpeech.speak(caption, TextToSpeech.QUEUE_FLUSH, null);
        sendResponseToMainActivity();
    }

    private void sendResponseToMainActivity() {
        System.out.println("Entering CaptionActivity sendResponseToMainActivity");
        Intent resultIntent = new Intent();
        setResult(Activity.RESULT_OK, resultIntent);
        finish();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }

    /**
     * Builds a Glass styled 'caption' (generated by server) view using the {@link CardBuilder} class.
     */
    private View buildView() {
        System.out.println("Entering CaptionActivity buildView");
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

        card.setText(caption);
        return card.getView();
    }

}
