package com.nitk.it.glassassistant;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.media.AudioManager;
import android.os.AsyncTask;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.Socket;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class SocketClientActivity extends Activity {

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    private CardScrollView mCardScroller;

    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    private View mView;

    private Socket socket;
    private File imageFile;
    private FileInputStream fileInputStream;
    private OutputStream outputStream;
    private DataOutputStream dataOutputStream;
    private byte [] imageBytes;
    private String caption;

    public class SendImageTask extends AsyncTask<File, Integer, Long> {

        @Override
        protected Long doInBackground(File... files) {
            try {
//                socket = new Socket(String.valueOf(R.string.server_address), R.integer.port);
                socket = new Socket("192.168.43.205",5000);
                fileInputStream = new FileInputStream(imageFile);
                Bitmap bitmap = BitmapFactory.decodeStream(fileInputStream);
                imageBytes = getBytesFromBitmap(bitmap);
                outputStream = socket.getOutputStream();
                dataOutputStream = new DataOutputStream(socket.getOutputStream());
                System.out.println("Sending size of image bytes....");
                dataOutputStream.writeInt(imageBytes.length);
                System.out.println(imageBytes.length);
                System.out.println("Sending image bytes....");
                outputStream.write(imageBytes);
                outputStream.flush();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }

        @Override
        protected void onProgressUpdate(Integer... values) {
            super.onProgressUpdate(values);
        }

        @Override
        protected void onPostExecute(Long aLong) {
            super.onPostExecute(aLong);
        }

    }

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        mView = buildView();

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });
        // Handle the TAP event.
        mCardScroller.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Plays disallowed sound to indicate that TAP actions are not supported.
                AudioManager am = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                am.playSoundEffect(Sounds.DISALLOWED);
            }
        });
        setContentView(mCardScroller);
        imageFile = (File) getIntent().getExtras().get("IMAGE");
        new SendImageTask().execute(imageFile);
        getResponseFromServer();
    }

    private void getResponseFromServer() {
        // TODO: Receive caption from server
        caption = "DUMMY CAPTION";
        Intent resultIntent = new Intent();
        resultIntent.putExtra("CAPTION", caption);
        setResult(Activity.RESULT_OK, resultIntent);
        finish();
    }

    private byte[] getBytesFromBitmap(Bitmap bitmap) {
        ByteArrayOutputStream stream = new ByteArrayOutputStream();
        // TODO: Must use strings and integers defined in values/strings.xml & integers.xml
        bitmap.compress(Bitmap.CompressFormat.JPEG, 5, stream);
        return stream.toByteArray();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mCardScroller.activate();
    }

    @Override
    protected void onPause() {
        mCardScroller.deactivate();
        super.onPause();
    }

    /**
     * View displayed while image is being sent and response is received.
     */
    private View buildView() {
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

        card.setText(R.string.sending_image_socket);
        return card.getView();
    }

}
